version: '3.9'
services:
  mysql_container:
    container_name: mysql_container
    hostname: mysql_container
    image: mysql:8
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_container:/var/lib/mysql 
    ports:
      - 3306:3306
    environment:
      TZ: Africa/Luanda
    env_file:
      - .env   